/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../src/angular2-tinymce.component';
import * as import2 from '@angular/forms';
const styles_TinymceComponent:any[] = ([] as any[]);
export const RenderType_TinymceComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_TinymceComponent,
  data: {}
}
);
export function View_TinymceComponent_0(l:any):import0.ɵViewDefinition {
      return import0.ɵvid(0,[(l()(),import0.ɵeld(0,(null as any),(null as any),0,'div',([] as any[]),[[
        8,
        'id',
        0
      ]
  ],(null as any),(null as any),(null as any),(null as any)))],(null as any),(ck,v) => {
    var co:import1.TinymceComponent = v.component;
    const currVal_0:any = import0.ɵinlineInterpolate(1,'',co.elementId,'');
    ck(v,0,0,currVal_0);
  });
}
function View_TinymceComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),2,'app-tinymce',([] as any[]),(null as any),(null as any),(null as any),View_TinymceComponent_0,RenderType_TinymceComponent)),
    import0.ɵdid(2187264,(null as any),0,import1.TinymceComponent,[
      import0.NgZone,
      'TINYMCE_CONFIG'
    ]
    ,(null as any),(null as any)),
    import0.ɵprd(2560,(null as any),import2.NG_VALUE_ACCESSOR,(p0_0:any) => {
      return [p0_0];
    },[import1.TinymceComponent])
  ]
  ,(null as any),(null as any));
}
export const TinymceComponentNgFactory:import0.ComponentFactory<import1.TinymceComponent> = import0.ɵccf('app-tinymce',import1.TinymceComponent,View_TinymceComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzoveGFtcHAvaHRkb2NzL2FuZ3VsYXIyLXRpbnltY2Uvc3JjL2FuZ3VsYXIyLXRpbnltY2UuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L3hhbXBwL2h0ZG9jcy9hbmd1bGFyMi10aW55bWNlL3NyYy9hbmd1bGFyMi10aW55bWNlLmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L3hhbXBwL2h0ZG9jcy9hbmd1bGFyMi10aW55bWNlL3NyYy9hbmd1bGFyMi10aW55bWNlLmNvbXBvbmVudC50cy5UaW55bWNlQ29tcG9uZW50Lmh0bWwiLCJuZzovLy9DOi94YW1wcC9odGRvY3MvYW5ndWxhcjItdGlueW1jZS9zcmMvYW5ndWxhcjItdGlueW1jZS5jb21wb25lbnQudHMuVGlueW1jZUNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxkaXYgaWQ9XCJ7e2VsZW1lbnRJZH19XCI+PC9kaXY+IiwiPGFwcC10aW55bWNlPjwvYXBwLXRpbnltY2U+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs2QkNBQTtRQUFBO1FBQUE7UUFBQTtNQUFBO0VBQUE7O0lBQUs7SUFBTCxTQUFLLFNBQUw7Ozs7O0lDQUE7Z0JBQUE7O01BQUE7SUFBQTtLQUFBO2dCQUFBO01BQUE7SUFBQTs7OzsifQ==
